# These are supported funding model platforms

github: [UsairimKamal786]
patreon: UsairimKamal786
open_collective: UsairimKamal786
ko_fi: UsairimKamal786
tidelift: # left this
community_bridge: UsairimKamal786
liberapay: UsairimKamal786
issuehunt: UsairimKamal786
lfx_crowdfunding: UsairimKamal786
polar: UsairimKamal786
buy_me_a_coffee: UsairimKamal786
thanks_dev: UsairimKamal786
custom: ['https://github.com/UsairimKamal786', 'https://patreon.com/UsairimKamal786']
